In [37]:
import pandas as pd
import numpy as np
import os

from pathlib import Path

In [2]:
os.getcwd()

'/Users/gurjitsingh/Desktop/DS_and_AI_projects/Whitefly_Risk_Intelligence/notebooks'

In [3]:
os.chdir("/Users/gurjitsingh/Desktop/DS_and_AI_projects/Whitefly_Risk_Intelligence")

In [4]:
os.getcwd()

'/Users/gurjitsingh/Desktop/DS_and_AI_projects/Whitefly_Risk_Intelligence'

### Function 1: load_and_validate_trap_metadata(path: Path)

In [13]:
METADATA_REQ_COLS = [
    'site_id', 
    'latitude', 
    'longitude'
]

In [95]:
# Function 1:
def load_and_validate_trap_metadata(path: Path) -> pd.DataFrame:
    """
    Loads and validates the trap metadata
    
    Inputs:
        - Path to trap metadata CSV file

    Outputs:
        - Trap metadata pandas df
    """
    print("Starting Function 1: Loading and validating trap metadata")
    
    # Read the trap metadata and store as data frame
    metadata_df = pd.read_csv(path, dtype={"site_id": "string"})

    # Verify if the parsed dataset is empty
    if metadata_df.empty:
        raise ValueError("The parsed trap metadata df is empty.")

    # Verify all the three required columns are present
    missing_cols = []
    for col in METADATA_REQ_COLS:
        if col not in metadata_df.columns.tolist():
            missing_cols.append(col)

    if len(missing_cols) != 0:
        raise ValueError(f"There are missing required columns in the parsed metadata: {missing_cols}")

    # Strip blank spaces (if any) from each of the site IDs
    metadata_df["site_id"] = metadata_df["site_id"].str.strip()

    # Validate if there are blank spaces as site IDs
    blank_site_ids = metadata_df.loc[metadata_df["site_id"] == "", ]
    if blank_site_ids.shape[0] != 0:
        raise ValueError(f"There are {len(blank_site_ids)} blank site IDs. Row indexes: {blank_site_ids.index.tolist()}")

    # Verify if the site ID column has NULL values
    missing_sites = metadata_df.loc[metadata_df["site_id"].isna(), ]
    if missing_sites.shape[0] != 0:
        raise ValueError(f"The 'site_id' column has {len(missing_sites)} missing values. Row indexes: {missing_sites.index.tolist()}")

    # Verify if there are duplicate site IDs
    duplicated_sites = metadata_df["site_id"].duplicated()
    if duplicated_sites.any():
        dup_values = metadata_df.loc[duplicated_sites, "site_id"].unique()
        raise ValueError(f"There are duplicated 'site_id' column values: {dup_values.tolist()}")

    # Verify if there are missing values in the Latitude column
    missing_latitude = metadata_df["latitude"].isna()
    if missing_latitude.any():
        raise ValueError(f"There are {missing_latitude.sum()} missing values in the 'latitude' column.")

    # Verify if there are missing values in the Longitude column
    missing_longitude = metadata_df["longitude"].isna()
    if missing_longitude.any():
        raise ValueError(f"There are {missing_longitude.sum()} missing values in the 'longitude' column.")

    # Verify if there are non-numeric values in the Latitude column
    # If not, then set the column dtype as float
    bad_latitude = pd.to_numeric(metadata_df["latitude"], errors="coerce").isna()
    if bad_latitude.any():
        bad_lat_rows = metadata_df.loc[bad_latitude, "latitude"]
        raise ValueError(f"There are non-numeric values in the column 'latitude': {bad_lat_rows.tolist()}")

    metadata_df["latitude"] = metadata_df["latitude"].astype("float")

    # Verify if there are non-numeric values in the Longitude column
    # If not, then set the column dtype as float
    bad_longitude = pd.to_numeric(metadata_df["longitude"], errors="coerce").isna()
    if bad_longitude.any():
        bad_lon_rows = metadata_df.loc[bad_longitude, "longitude"]
        raise ValueError(f"There are non-numeric values in the column 'longitude': {bad_lon_rows.tolist()}")

    metadata_df["longitude"] = metadata_df["longitude"].astype("float")

    # Verify if the Latitude values lie in the valid range
    if (metadata_df["latitude"].min() < -90) or (metadata_df["latitude"].max() > 90):
        raise ValueError("Latitude column has values outside the permissible bounds.")

    # Verify if the Longitude values lie in the valid range
    if (metadata_df["longitude"].min() < -180) or (metadata_df["longitude"].max() > 180):
        raise ValueError("Longitude column has values outside the permissible bounds.")

    return metadata_df

In [30]:
df = pd.read_csv("data/interim/trap_metadata.csv")
df.head()

   site_id trap_label   latitude  longitude  status first_report last_report
0    29221   Trap 101  31.466030 -83.465008  Active   2020-04-22  2026-06-22
1    29222   Trap 102  31.465087 -83.405028  Active   2020-04-22  2026-06-22
2    29224   Trap 104  31.557827 -83.480183  Active   2020-04-22  2026-06-22
3    29225   Trap 105  31.541213 -83.573040  Active   2020-04-22  2026-06-15
4    29226   Trap 106  31.524275 -83.662878  Active   2020-04-22  2026-06-15

In [31]:
func_1_test_1_df = df.copy()

#### Test 1: Dropping a required column

In [ ]:
func_1_test_1_df = func_1_test_1_df.drop("latitude", axis=1)
func_1_test_1_df.head()

   site_id trap_label  longitude  status first_report last_report
0    29221   Trap 101 -83.465008  Active   2020-04-22  2026-06-22
1    29222   Trap 102 -83.405028  Active   2020-04-22  2026-06-22
2    29224   Trap 104 -83.480183  Active   2020-04-22  2026-06-22
3    29225   Trap 105 -83.573040  Active   2020-04-22  2026-06-15
4    29226   Trap 106 -83.662878  Active   2020-04-22  2026-06-15

In [33]:
func_1_test_1_df.to_csv("data/interim/func_1_test_1_df.csv", index=False)

In [37]:
path_1 = Path("data/interim/func_1_test_1_df.csv")
load_and_validate_trap_metadata(path_1)

Starting Function 1: Loading and validating trap metadata

ValueError: There are missing required columns in the parsed metadata: ['latitude']

#### Test 2: Set one site_id to an empty blank space string

In [69]:
func_1_test_2_df = df.copy()

# First set the dtype of the column as string
func_1_test_2_df["site_id"] = func_1_test_2_df["site_id"].astype("string")

func_1_test_2_df.iloc[1, 0] = " "
func_1_test_2_df.head()

  site_id trap_label   latitude  longitude  status first_report last_report
0   29221   Trap 101  31.466030 -83.465008  Active   2020-04-22  2026-06-22
1           Trap 102  31.465087 -83.405028  Active   2020-04-22  2026-06-22
2   29224   Trap 104  31.557827 -83.480183  Active   2020-04-22  2026-06-22
3   29225   Trap 105  31.541213 -83.573040  Active   2020-04-22  2026-06-15
4   29226   Trap 106  31.524275 -83.662878  Active   2020-04-22  2026-06-15

In [70]:
func_1_test_2_df.to_csv("data/interim/func_1_test_2_df.csv", index=False)

In [71]:
path_2 = Path("data/interim/func_1_test_2_df.csv")
load_and_validate_trap_metadata(path_2)

Starting Function 1: Loading and validating trap metadata

ValueError: There are 1 blank site IDs. Row indexes: [1]

#### Test 3: Set one site_id to a missing value

In [82]:
func_1_test_3_df = df.copy()

func_1_test_3_df.iloc[1:4, 0] = pd.NA
func_1_test_3_df.head()

   site_id trap_label   latitude  longitude  status first_report last_report
0  29221.0   Trap 101  31.466030 -83.465008  Active   2020-04-22  2026-06-22
1      NaN   Trap 102  31.465087 -83.405028  Active   2020-04-22  2026-06-22
2      NaN   Trap 104  31.557827 -83.480183  Active   2020-04-22  2026-06-22
3      NaN   Trap 105  31.541213 -83.573040  Active   2020-04-22  2026-06-15
4  29226.0   Trap 106  31.524275 -83.662878  Active   2020-04-22  2026-06-15

In [83]:
func_1_test_3_df.to_csv("data/interim/func_1_test_3_df.csv", index=False)

In [84]:
path_3 = Path("data/interim/func_1_test_3_df.csv")
load_and_validate_trap_metadata(path_3)

Starting Function 1: Loading and validating trap metadata

ValueError: The 'site_id' column has 3 missing values. Row indexes: [1, 2, 3]

#### Test 4: Copy one site_id onto another row

In [86]:
func_1_test_4_df = df.copy()

func_1_test_4_df.iloc[1:3, 0] = func_1_test_4_df.iloc[4,0]
func_1_test_4_df.head()

   site_id trap_label   latitude  longitude  status first_report last_report
0    29221   Trap 101  31.466030 -83.465008  Active   2020-04-22  2026-06-22
1    29226   Trap 102  31.465087 -83.405028  Active   2020-04-22  2026-06-22
2    29226   Trap 104  31.557827 -83.480183  Active   2020-04-22  2026-06-22
3    29225   Trap 105  31.541213 -83.573040  Active   2020-04-22  2026-06-15
4    29226   Trap 106  31.524275 -83.662878  Active   2020-04-22  2026-06-15

In [87]:
func_1_test_4_df.to_csv("data/interim/func_1_test_4_df.csv", index=False)

In [96]:
path_4 = Path("data/interim/func_1_test_4_df.csv")
load_and_validate_trap_metadata(path_4)

Starting Function 1: Loading and validating trap metadata

ValueError: There are duplicated 'site_id' column values: ['29226']

#### Test 5: Set one latitude to 'abc'

In [97]:
func_1_test_5_df = df.copy()

func_1_test_5_df['latitude'] = func_1_test_5_df['latitude'].astype("string")

func_1_test_5_df.iloc[2,2] = "abc"
func_1_test_5_df.head()

   site_id trap_label   latitude  longitude  status first_report last_report
0    29221   Trap 101   31.46603 -83.465008  Active   2020-04-22  2026-06-22
1    29222   Trap 102  31.465087 -83.405028  Active   2020-04-22  2026-06-22
2    29224   Trap 104        abc -83.480183  Active   2020-04-22  2026-06-22
3    29225   Trap 105  31.541213 -83.573040  Active   2020-04-22  2026-06-15
4    29226   Trap 106  31.524275 -83.662878  Active   2020-04-22  2026-06-15

In [98]:
func_1_test_5_df.to_csv("data/interim/func_1_test_5_df.csv", index=False)

In [99]:
path_5 = Path("data/interim/func_1_test_5_df.csv")
load_and_validate_trap_metadata(path_5)

Starting Function 1: Loading and validating trap metadata

ValueError: There are non-numeric values in the column 'latitude': ['abc']

#### Test 6: Set one longitude to missing

In [100]:
func_1_test_6_df = df.copy()

func_1_test_6_df.iloc[2,3] = pd.NA
func_1_test_6_df.head()

   site_id trap_label   latitude  longitude  status first_report last_report
0    29221   Trap 101  31.466030 -83.465008  Active   2020-04-22  2026-06-22
1    29222   Trap 102  31.465087 -83.405028  Active   2020-04-22  2026-06-22
2    29224   Trap 104  31.557827        NaN  Active   2020-04-22  2026-06-22
3    29225   Trap 105  31.541213 -83.573040  Active   2020-04-22  2026-06-15
4    29226   Trap 106  31.524275 -83.662878  Active   2020-04-22  2026-06-15

In [101]:
func_1_test_6_df.to_csv("data/interim/func_1_test_6_df.csv", index=False)

In [102]:
path_6 = Path("data/interim/func_1_test_6_df.csv")
load_and_validate_trap_metadata(path_6)

Starting Function 1: Loading and validating trap metadata

ValueError: There are 1 missing values in the 'longitude' column.

#### Test 7: Set one latitude to 91

In [103]:
func_1_test_7_df = df.copy()

func_1_test_7_df.iloc[2,2] = 91
func_1_test_7_df.head()

   site_id trap_label   latitude  longitude  status first_report last_report
0    29221   Trap 101  31.466030 -83.465008  Active   2020-04-22  2026-06-22
1    29222   Trap 102  31.465087 -83.405028  Active   2020-04-22  2026-06-22
2    29224   Trap 104  91.000000 -83.480183  Active   2020-04-22  2026-06-22
3    29225   Trap 105  31.541213 -83.573040  Active   2020-04-22  2026-06-15
4    29226   Trap 106  31.524275 -83.662878  Active   2020-04-22  2026-06-15

In [104]:
func_1_test_7_df.to_csv("data/interim/func_1_test_7_df.csv", index=False)

In [105]:
path_7 = Path("data/interim/func_1_test_7_df.csv")
load_and_validate_trap_metadata(path_7)

Starting Function 1: Loading and validating trap metadata

ValueError: Latitude column has values outside the permissible bounds.

#### Test 8: Set one longitude to -181

In [106]:
func_1_test_8_df = df.copy()

func_1_test_8_df.iloc[2,3] = -181
func_1_test_8_df.head()

   site_id trap_label   latitude   longitude  status first_report last_report
0    29221   Trap 101  31.466030  -83.465008  Active   2020-04-22  2026-06-22
1    29222   Trap 102  31.465087  -83.405028  Active   2020-04-22  2026-06-22
2    29224   Trap 104  31.557827 -181.000000  Active   2020-04-22  2026-06-22
3    29225   Trap 105  31.541213  -83.573040  Active   2020-04-22  2026-06-15
4    29226   Trap 106  31.524275  -83.662878  Active   2020-04-22  2026-06-15

In [107]:
func_1_test_8_df.to_csv("data/interim/func_1_test_8_df.csv", index=False)

In [108]:
path_8 = Path("data/interim/func_1_test_8_df.csv")
load_and_validate_trap_metadata(path_8)

Starting Function 1: Loading and validating trap metadata

ValueError: Longitude column has values outside the permissible bounds.

### Function 2: load_and_validate_weekly_trap_counts(path: Path)

In [5]:
WEEKLY_TRAP_COUNTS_REQ_COLS = [
    "site_id",
    "year",
    "date_collected",
    "whitefly_count"
]

In [6]:
def load_and_validate_weekly_trap_counts(path: Path) -> pd.DataFrame:
    """
    Loads and validates weekly whitefly trap counts

    Inputs:
        - Path to weekly trap counts CSV file

    Outputs:
        - Weekly whitefly counts pandas df
    """
    count_df = pd.read_csv(path, dtype={"site_id": "string"})

    # Validate against empty df
    if count_df.empty:
        raise ValueError("Parsed weekly whitefly trap counts df is empty.")

    # Validate if the required columns exist
    missing_req_cols = []
    for col in WEEKLY_TRAP_COUNTS_REQ_COLS:
        if col not in count_df.columns.tolist():
            missing_req_cols.append(col)

    if len(missing_req_cols) != 0:
        raise ValueError(
            f"There are missing required columns in the parsed trap counts df: {missing_req_cols}"
        )

    # Strip blank spaces from the 'site_id' column values
    count_df["site_id"] = count_df["site_id"].str.strip()

    # Check for blank site_id column values
    blank_sites = count_df.loc[
        count_df["site_id"] == "",
        "site_id"
    ].index.tolist()

    if len(blank_sites) != 0:
        raise ValueError(
            f"There are {len(blank_sites)} blank site_id values. Row indexes: {blank_sites}"
        )

    # Validate against missing site_id
    missing_sites = count_df.loc[
        count_df["site_id"].isna(), "site_id"
        ].index.tolist()
    
    if len(missing_sites) != 0:
        raise ValueError(
            f"There are {len(missing_sites)} missing site IDs. Row indexes: {missing_sites}"
            )

    # Parse dates with invalid values converted to NaT
    count_df["date_collected"] = pd.to_datetime(count_df["date_collected"], errors="coerce")

    # Normalize to remove time stamps from date column
    count_df["date_collected"] = count_df["date_collected"].dt.normalize()

    # Validate against missing collection dates
    missing_dates = count_df.loc[
        count_df["date_collected"].isna(), "date_collected"
        ].index.tolist()
    
    if len(missing_dates) != 0:
        raise ValueError(
            f"There are {len(missing_dates)} missing dates of sample collection. Row indexes: {missing_dates}"
            )

    # Verify unique 'site_id x date_collected'
    duplicate_sites_dates = (
        count_df.groupby(["site_id", "date_collected"])
        .size()
        .reset_index(name = "count")
        .query("count > 1")
    )
    
    if duplicate_sites_dates.shape[0] != 0:
        raise ValueError(
            f"There are duplicate 'site_id x date_collected' values: {duplicate_sites_dates[['site_id', 'date_collected']].values.tolist()}"
            )

    # Validate 'year' column
    # Convert the column to numeric dtype
    count_df["year"] = pd.to_numeric(count_df["year"])

    # Validate for missing year column values
    missing_year = count_df.loc[
        count_df["year"].isna(), "year"
        ].index.tolist()
    
    if len(missing_year) != 0:
        raise ValueError(
            f"There are {len(missing_year)} missing values in the 'year' column. Row indexes: {missing_year}"
            )
    
    # Validate for finite year values
    infinite_years = count_df.loc[
        (count_df["year"] == np.inf) | 
        (count_df["year"] == -np.inf),
        "year"
    ].index.tolist()

    if len(infinite_years) != 0:
        raise ValueError(
            f"There are {len(infinite_years)} infinite year values. "
            f"Row indexes: {infinite_years}"
            )

    # Validate for fractional year values
    fractional_years = count_df.loc[count_df["year"] % 1 != 0, "year"].index.tolist()
    if len(fractional_years) != 0:
        raise ValueError(
            f"There are {len(fractional_years)} invalid fraction year values in the column 'year'. " 
            f"Row indexes: {fractional_years}"
        )

    # Validate for negative year values
    negative_years = count_df.loc[
        count_df["year"] < 0,
        "year"
    ].index.tolist()

    if len(negative_years) != 0:
        raise ValueError(
            f"There are {len(negative_years)} rows with negative year values. " 
            f"Row indexes: {negative_years}"
        )

    # Convert year column to integer dtype
    count_df["year"] = count_df["year"].astype("int")

    # Validate for year value match
    non_matching_years = count_df.index[
        count_df["year"] != count_df["date_collected"].dt.year
        ].tolist()

    if len(non_matching_years) != 0:
        raise ValueError(
            f"There are {len(non_matching_years)} rows with non-matching years in the 'year' and 'date_collected' columns."
            )

    # Validate 'whitefly_count' column
    # Convert column to numeric dtype
    count_df["whitefly_count"] = pd.to_numeric(count_df["whitefly_count"])

    # Validate for missing counts
    missing_count = count_df.loc[
        count_df["whitefly_count"].isna(), "whitefly_count"
    ].index.tolist()

    if len(missing_count) != 0:
        raise ValueError(
            f"There are {len(missing_count)} missing whitefly count values. Row indexes: {missing_count}"
        )

    # Validate for finite counts
    infinite_counts = count_df.loc[
        (count_df["whitefly_count"] == np.inf) | 
        (count_df["whitefly_count"] == -np.inf),
        "whitefly_count"
    ].index.tolist()

    if len(infinite_counts) != 0:
        raise ValueError(
            f"There are {len(infinite_counts)} infinite count values. "
            f"Row indexes: {infinite_counts}"
            )

    # Validate for fractional counts
    fractional_counts = count_df.loc[count_df["whitefly_count"] % 1 != 0, "whitefly_count"].index.tolist()
    if len(fractional_counts) != 0:
        raise ValueError(
            f"There are {len(fractional_counts)} invalid fractional whitefly counts in the column 'whitefly_count'. " 
            f"Row indexes: {fractional_counts}"
        )

    # Validate for negative count values
    negative_counts = count_df.loc[
        count_df["whitefly_count"] < 0,
        "whitefly_count"
    ].index.tolist()

    if len(negative_counts) != 0:
        raise ValueError(
            f"There are {len(negative_counts)} rows with negative whitefly counts. Row indexes: {negative_counts}"
        )

    # Convert the 'whitefly_count' column to integer dtype
    count_df["whitefly_count"] = count_df["whitefly_count"].astype("int")

    return count_df

In [27]:
df2 = pd.read_csv("data/processed/stopwhitefly_trap_weekly_counts_with_metadata.csv")
df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221,2020,2024-04-22,2020-04-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,29221,2020,2024-04-28,2020-04-28,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,29221,2020,2024-05-06,2020-05-06,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221,2020,2024-05-15,2020-05-15,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221,2020,2024-05-22,2020-05-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

#### Test 1: Missing required column

In [15]:
func_2_test_1_df2 = df2.copy()

In [16]:
func_2_test_1_df2= func_2_test_1_df2.drop("site_id", axis=1)

func_2_test_1_df2.to_csv("data/interim/func_2_test_1_df2.csv", index=False)

In [17]:
path_21 = Path("data/interim/func_2_test_1_df2.csv")

load_and_validate_weekly_trap_counts(path_21)

ValueError: There are missing required columns in the parsed trap counts df: ['site_id']

#### Test 2: Missing site_id fail

In [28]:
func_2_test_2_df2 = df2.copy()
func_2_test_2_df2.loc[func_2_test_2_df2.index[1:3], "site_id"] = pd.NA
func_2_test_2_df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221.0,2020,2024-04-22,2020-04-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,NaN,2020,2024-04-28,2020-04-28,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,NaN,2020,2024-05-06,2020-05-06,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221.0,2020,2024-05-15,2020-05-15,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221.0,2020,2024-05-22,2020-05-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

In [29]:
func_2_test_2_df2.to_csv("data/interim/func_2_test_2_df2.csv", index=False)

In [30]:
path_22 = Path("data/interim/func_2_test_2_df2.csv")
load_and_validate_weekly_trap_counts(path_22)

ValueError: There are 2 missing site IDs. Row indexes: [1, 2]

#### Test 3: Duplicate site_id x date_collected

In [31]:
func_2_test_3_df2 = df2.copy()

func_2_test_3_df2.loc[func_2_test_3_df2.index[1:3], "date_collected"] = func_2_test_3_df2["date_collected"][0]
func_2_test_3_df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221,2020,2024-04-22,2020-04-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,29221,2020,2024-04-28,2020-04-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,29221,2020,2024-05-06,2020-04-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221,2020,2024-05-15,2020-05-15,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221,2020,2024-05-22,2020-05-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

In [32]:
func_2_test_3_df2.to_csv("data/interim/func_2_test_3_df2.csv", index=False)

In [33]:
path_23 = Path("data/interim/func_2_test_3_df2.csv")
load_and_validate_weekly_trap_counts(path_23)

ValueError: There are duplicate 'site_id x date_collected' values: [['29221', Timestamp('2020-04-22 00:00:00')]]

#### Test 4: Invalid whitefly counts fail- missing values

In [34]:
func_2_test_4_df2 = df2.copy()

func_2_test_4_df2.loc[func_2_test_4_df2.index[1:3], "whitefly_count"] = pd.NA
func_2_test_4_df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221,2020,2024-04-22,2020-04-22,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,29221,2020,2024-04-28,2020-04-28,NaN,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,29221,2020,2024-05-06,2020-05-06,NaN,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221,2020,2024-05-15,2020-05-15,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221,2020,2024-05-22,2020-05-22,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

In [35]:
func_2_test_4_df2.to_csv("data/interim/func_2_test_4_df2.csv", index=False)

In [38]:
path_24 = Path("data/interim/func_2_test_4_df2.csv")
load_and_validate_weekly_trap_counts(path_24)

ValueError: There are 2 missing whitefly count values. Row indexes: [1, 2]

#### Test 5: Invalid whitefly counts fail- negative values

In [42]:
func_2_test_5_df2 = df2.copy()

func_2_test_5_df2.loc[func_2_test_5_df2.index[1:3], "whitefly_count"] = -4
func_2_test_5_df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221,2020,2024-04-22,2020-04-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,29221,2020,2024-04-28,2020-04-28,-4,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,29221,2020,2024-05-06,2020-05-06,-4,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221,2020,2024-05-15,2020-05-15,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221,2020,2024-05-22,2020-05-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

In [43]:
func_2_test_5_df2.to_csv("data/interim/func_2_test_5_df2.csv", index=False)

In [44]:
path_25 = Path("data/interim/func_2_test_5_df2.csv")
load_and_validate_weekly_trap_counts(path_25)

ValueError: There are 2 rows with negative whitefly counts. Row indexes: [1, 2]

#### Test 6: Invalid whitefly counts fail- fractional values

In [46]:
func_2_test_6_df2 = df2.copy()

func_2_test_6_df2["whitefly_count"] = func_2_test_6_df2["whitefly_count"].astype("float")
func_2_test_6_df2.loc[func_2_test_6_df2.index[1:3], "whitefly_count"] = 2.5
func_2_test_6_df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221,2020,2024-04-22,2020-04-22,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,29221,2020,2024-04-28,2020-04-28,2.5,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,29221,2020,2024-05-06,2020-05-06,2.5,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221,2020,2024-05-15,2020-05-15,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221,2020,2024-05-22,2020-05-22,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

In [47]:
func_2_test_6_df2.to_csv("data/interim/func_2_test_6_df2.csv", index=False)

In [48]:
path_26 = Path("data/interim/func_2_test_6_df2.csv")
load_and_validate_weekly_trap_counts(path_26)

ValueError: There are 2 invalid fractional whitefly counts in the column 'whitefly_count'. Row indexes: [1, 2]

#### Test 7: Invalid whitefly counts- infinite values

In [49]:
func_2_test_7_df2 = df2.copy()

func_2_test_7_df2["whitefly_count"] = func_2_test_7_df2["whitefly_count"].astype("float")
func_2_test_7_df2.loc[func_2_test_7_df2.index[1:3], "whitefly_count"] = np.inf
func_2_test_7_df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221,2020,2024-04-22,2020-04-22,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,29221,2020,2024-04-28,2020-04-28,inf,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,29221,2020,2024-05-06,2020-05-06,inf,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221,2020,2024-05-15,2020-05-15,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221,2020,2024-05-22,2020-05-22,0.0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

In [50]:
func_2_test_7_df2.to_csv("data/interim/func_2_test_7_df2.csv", index=False)

In [51]:
path_27 = Path("data/interim/func_2_test_7_df2.csv")
load_and_validate_weekly_trap_counts(path_27)

ValueError: There are 2 infinite count values. Row indexes: [1, 2]

#### Test 8: Blank site_id fail

In [53]:
func_2_test_8_df2 = df2.copy()

func_2_test_8_df2["site_id"] = func_2_test_8_df2["site_id"].astype("str")

func_2_test_8_df2.loc[func_2_test_8_df2.index[1:3], "site_id"] = " "
func_2_test_8_df2.head()

,site_id,year,plotted_date,date_collected,whitefly_count,trap_label,latitude,longitude,status,first_report,last_report
0,29221,2020,2024-04-22,2020-04-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
1,,2020,2024-04-28,2020-04-28,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
2,,2020,2024-05-06,2020-05-06,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
3,29221,2020,2024-05-15,2020-05-15,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22
4,29221,2020,2024-05-22,2020-05-22,0,Trap 101,31.46603,-83.465008,Active,2020-04-22,2026-06-22

In [54]:
func_2_test_8_df2.to_csv("data/interim/func_2_test_8_df2.csv", index=False)

In [55]:
path_28 = Path("data/interim/func_2_test_8_df2.csv")
load_and_validate_weekly_trap_counts(path_28)

ValueError: There are 2 blank site_id values. Row indexes: [1, 2]